version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/10-account"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/20-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/lambda-producer-handler"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/lambda-db-password-rotation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/lambda-alarm-notification"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/legacy-dashboard-redirect-viewer-request"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/public-api-cloud-front-viewer-request"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/lambda-front-end-revalidation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/lambda-retrieve-user-permission-set"
    schedule:
      interval: "weekly"

